### PR TITLE
clarifying the example of multi-line code blocks

### PR DESCRIPTION
**Pull request by stevenewsted**

### CODE REVIEW

**Comment by ironicbadger** [comment]
My intention was to explain this...

~~~
code block with bash highlighting
```bash
echo test
```

code block with python highlighting
```python
print("Hello World")
```
~~~

**Comment by stevenewsted** [comment]
gotcha. it looked like a typo to me. would it make more sense to link to the official docs instead of giving examples?

**Comment by ironicbadger** [comment]
Probably.

**Comment by ironicbadger** [comment]
Commit 0d615d71290c00b21384e59e764138846ae88b43

**Pull request closed without merging**
